import type { Readable } from 'node:stream';

/**
 * Two zones, decided on day one rather than when the first sensitive file
 * arrives.
 *
 * - `public` — catalog images. Anyone may read them, guests included, and
 *   clients may cache them forever (keys are never reused).
 * - `private` — files a customer hands us: a document to print, a photo to put
 *   on a mug. A print document can be an ID copy. These are reachable only
 *   through a short-lived signed link issued after the caller's right to the
 *   file was checked.
 *
 * Built with one zone, print uploads would later take the same path as product
 * photos and nothing would notice — the public URL would simply work.
 */
export type StorageZone = 'public' | 'private';

export const STORAGE_ZONES: readonly StorageZone[] = ['public', 'private'];

export interface StoredObject {
  stream: Readable;
  size: number;
}

/**
 * Where the client sends the bytes of a direct upload. The file never passes
 * through the API process when the driver is S3: the URL is a presigned PUT to
 * the bucket. With the local driver it points at `PUT /files/uploads/:token`,
 * and the client cannot tell the two apart — same method, same headers rule.
 *
 * `headers` must be sent **exactly** — they are part of the signature, and the
 * declared `Content-Length` is what caps the upload's size.
 */
export interface UploadTarget {
  method: 'PUT';
  url: string;
  headers: Record<string, string>;
  expires_at: Date;
}

export interface UploadTargetOptions {
  /** Exact byte count the client declared. A different body is refused by the store. */
  bytes: number;
  contentType: string;
  ttlSeconds: number;
}

export interface DownloadUrlOptions {
  /** Offered to the reader as the file name (`Content-Disposition: attachment`). */
  filename: string | null;
  contentType: string | null;
  ttlSeconds: number;
}

/**
 * Where bytes live. The application never builds a filesystem path or a bucket
 * URL itself — moving from this laptop to MinIO or S3 is a different
 * implementation of these methods and one `.env` value.
 *
 * Keys are always generated by the server (`storage-keys.ts`) and validated
 * again by every implementation, so no client string ever becomes a path.
 */
export interface StorageDriver {
  put(zone: StorageZone, key: string, bytes: Buffer): Promise<void>;
  /** `null` when the object does not exist — a missing file is an answer, not an error. */
  open(zone: StorageZone, key: string): Promise<StoredObject | null>;
  delete(zone: StorageZone, key: string): Promise<void>;
  exists(zone: StorageZone, key: string): Promise<boolean>;
  /** Size in bytes, or `null` when the object does not exist. */
  size(zone: StorageZone, key: string): Promise<number | null>;
  /**
   * The first `bytes` bytes (fewer for a smaller file), or `null` when missing.
   * Enough to identify a file type without reading a 50 MB document.
   */
  readHead(zone: StorageZone, key: string, bytes: number): Promise<Buffer | null>;
  /** A short-lived link the client uploads one object to, directly. */
  uploadTarget(zone: StorageZone, key: string, options: UploadTargetOptions): Promise<UploadTarget>;
  /**
   * A short-lived link to read one **private** object. The caller checked the
   * reader's right first — the link is the permission.
   */
  downloadUrl(key: string, options: DownloadUrlOptions): Promise<string>;
}

let current: StorageDriver | undefined;

export function setStorageDriver(driver: StorageDriver): void {
  current = driver;
}

/**
 * The configured driver. Throws when `configureMedia()` never ran, so a missing
 * wire-up fails on the first upload with a clear message instead of writing
 * nowhere.
 */
export function storageDriver(): StorageDriver {
  if (!current) {
    throw new Error('Storage driver not configured — call configureMedia() in buildApp()');
  }
  return current;
}
