import type { Readable } from 'node:stream';

/**
 * Two zones, decided on day one rather than when the first sensitive file
 * arrives.
 *
 * - `public` — catalog images. Anyone may read them, guests included, and
 *   clients may cache them forever (keys are never reused).
 * - `private` — files a customer hands us: a document to print, a photo to put
 *   on a mug. A print document can be an ID copy. These are reachable only
 *   through a short-lived signed link (see `signed-url.ts`) issued after the
 *   caller's right to the file was checked.
 *
 * Built with one zone, print uploads would later take the same path as product
 * photos and nothing would notice — the public URL would simply work.
 */
export type StorageZone = 'public' | 'private';

export const STORAGE_ZONES: readonly StorageZone[] = ['public', 'private'];

export interface StoredObject {
  stream: Readable;
  size: number;
}

/**
 * Where bytes live. The application never builds a filesystem path or a bucket
 * URL itself — moving from this laptop to a server disk, MinIO or S3 is a new
 * implementation of these four methods and one `.env` value.
 *
 * Keys are always generated by the server (`storage-keys.ts`) and validated
 * again by every implementation, so no client string ever becomes a path.
 */
export interface StorageDriver {
  put(zone: StorageZone, key: string, bytes: Buffer): Promise<void>;
  /** `null` when the object does not exist — a missing file is an answer, not an error. */
  open(zone: StorageZone, key: string): Promise<StoredObject | null>;
  delete(zone: StorageZone, key: string): Promise<void>;
  exists(zone: StorageZone, key: string): Promise<boolean>;
}

let current: StorageDriver | undefined;

export function setStorageDriver(driver: StorageDriver): void {
  current = driver;
}

/**
 * The configured driver. Throws when `configureMedia()` never ran, so a missing
 * wire-up fails on the first upload with a clear message instead of writing
 * nowhere.
 */
export function storageDriver(): StorageDriver {
  if (!current) {
    throw new Error('Storage driver not configured — call configureMedia() in buildApp()');
  }
  return current;
}
